2025-07-09 13:50:05,714 [INFO] django.utils.autoreload: C:\Users\CPT-003\Desktop\CRM\crm_api\users\serializers.py changed, reloading.
2025-07-09 13:50:09,168 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2025-07-09 13:51:15,207 [INFO] django.server: "GET /api/tenant/modules/ HTTP/1.1" 200 146
2025-07-09 13:51:15,292 [INFO] core: Listing tenants: [2] for tenant proliance
2025-07-09 13:51:15,294 [INFO] django.server: "GET /api/tenant/tenants/ HTTP/1.1" 200 365
2025-07-09 13:52:38,228 [INFO] django.server: "GET /api/tenant/modules/ HTTP/1.1" 200 146
2025-07-09 13:52:38,366 [INFO] core: Listing tenants: [2] for tenant proliance
2025-07-09 13:52:38,368 [INFO] django.server: "GET /api/tenant/tenants/ HTTP/1.1" 200 365
2025-07-09 13:53:15,463 [INFO] django.server: "GET /api/tenant/modules/ HTTP/1.1" 200 146
2025-07-09 13:53:15,904 [INFO] core: Listing tenants: [2] for tenant proliance
2025-07-09 13:53:15,906 [INFO] django.server: "GET /api/tenant/tenants/ HTTP/1.1" 200 365
2025-07-09 13:54:41,207 [INFO] django.server: "GET /api/tenant/modules/ HTTP/1.1" 200 146
2025-07-09 13:54:41,321 [INFO] core: Listing tenants: [2] for tenant proliance
2025-07-09 13:54:41,322 [INFO] django.server: "GET /api/tenant/tenants/ HTTP/1.1" 200 365
2025-07-09 13:56:09,231 [INFO] django.utils.autoreload: C:\Users\CPT-003\Desktop\CRM\crm_api\users\serializers.py changed, reloading.
2025-07-09 13:56:17,379 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2025-07-09 13:58:27,201 [INFO] django.server: "GET /api/tenant/modules/ HTTP/1.1" 200 146
2025-07-09 13:58:27,362 [INFO] core: Listing tenants: [2] for tenant proliance
2025-07-09 13:58:27,363 [INFO] django.server: "GET /api/tenant/tenants/ HTTP/1.1" 200 365
2025-07-09 13:58:30,753 [ERROR] users: Validation error for tenant proliance: {'profile': [ErrorDetail(string='This field is required.', code='required')], 'documents': [{'title': [ErrorDetail(string='This field is required.', code='required')], 'file': [ErrorDetail(string='No file was submitted.', code='required')]}, {'title': [ErrorDetail(string='This field is required.', code='required')], 'file': [ErrorDetail(string='No file was submitted.', code='required')]}, {'title': [ErrorDetail(string='This field is required.', code='required')], 'file': [ErrorDetail(string='No file was submitted.', code='required')]}, {'title': [ErrorDetail(string='This field is required.', code='required')], 'file': [ErrorDetail(string='No file was submitted.', code='required')]}]}
2025-07-09 13:58:30,756 [WARNING] django.request: Bad Request: /api/user/create/
2025-07-09 13:58:30,756 [WARNING] django.server: "POST /api/user/create/ HTTP/1.1" 400 370
2025-07-09 14:00:00,187 [INFO] django.utils.autoreload: C:\Users\CPT-003\Desktop\CRM\crm_api\users\serializers.py changed, reloading.
2025-07-09 14:00:02,711 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2025-07-09 14:00:17,751 [INFO] django.utils.autoreload: C:\Users\CPT-003\Desktop\CRM\crm_api\users\views.py changed, reloading.
2025-07-09 14:00:20,706 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2025-07-09 14:01:41,172 [INFO] django.utils.autoreload: C:\Users\CPT-003\Desktop\CRM\crm_api\lumina_care\settings.py changed, reloading.
2025-07-09 14:01:44,237 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2025-07-09 14:01:58,930 [INFO] django.utils.autoreload: C:\Users\CPT-003\Desktop\CRM\crm_api\lumina_care\settings.py changed, reloading.
2025-07-09 14:02:10,778 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2025-07-09 14:02:47,674 [INFO] django.server: "POST /api/token/ HTTP/1.1" 200 956
2025-07-09 14:03:02,038 [INFO] users: User created: tmerr@prolianceltd.com (ID: 19) for tenant proliance
2025-07-09 14:03:02,049 [INFO] users: User created: tmerr@prolianceltd.com (ID: 19) for tenant proliance
2025-07-09 14:03:02,050 [INFO] django.server: "POST /api/user/create/ HTTP/1.1" 201 856
2025-07-09 14:09:08,917 [INFO] django.server: "OPTIONS /api/token/ HTTP/1.1" 200 0
2025-07-09 14:09:12,453 [INFO] django.server: "POST /api/token/ HTTP/1.1" 200 956
2025-07-09 14:09:12,862 [INFO] django.server: "GET /api/token/validate/ HTTP/1.1" 200 372
2025-07-09 14:09:12,991 [INFO] django.server: "GET /api/token/validate/ HTTP/1.1" 200 372
2025-07-09 14:09:15,648 [INFO] django.server: "GET /api/tenant/modules/ HTTP/1.1" 200 146
2025-07-09 14:09:15,762 [INFO] django.server: "GET /api/tenant/modules/ HTTP/1.1" 200 146
2025-07-09 14:09:15,873 [INFO] core: Listing tenants: [2] for tenant proliance
2025-07-09 14:09:15,874 [INFO] django.server: "GET /api/tenant/tenants/ HTTP/1.1" 200 365
2025-07-09 14:09:15,979 [INFO] core: Listing tenants: [2] for tenant proliance
2025-07-09 14:09:15,980 [INFO] django.server: "GET /api/tenant/tenants/ HTTP/1.1" 200 365
2025-07-09 14:12:23,329 [ERROR] users: Validation error for tenant proliance: {'profile': [ErrorDetail(string='This field is required.', code='required')], 'modules': [ErrorDetail(string='Incorrect type. Expected pk value, received list.', code='incorrect_type')], 'documents': [{'title': [ErrorDetail(string='This field is required.', code='required')], 'file': [ErrorDetail(string='No file was submitted.', code='required')]}, {'title': [ErrorDetail(string='This field is required.', code='required')], 'file': [ErrorDetail(string='No file was submitted.', code='required')]}]}
2025-07-09 14:12:23,331 [WARNING] django.request: Bad Request: /api/user/create/
2025-07-09 14:12:23,331 [WARNING] django.server: "POST /api/user/create/ HTTP/1.1" 400 290
2025-07-09 14:13:23,009 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2025-07-09 14:13:59,590 [ERROR] users: Validation error for tenant proliance: {'profile': [ErrorDetail(string='This field is required.', code='required')], 'modules': [ErrorDetail(string='Incorrect type. Expected pk value, received list.', code='incorrect_type')], 'documents': [{'title': [ErrorDetail(string='This field is required.', code='required')], 'file': [ErrorDetail(string='No file was submitted.', code='required')]}, {'title': [ErrorDetail(string='This field is required.', code='required')], 'file': [ErrorDetail(string='No file was submitted.', code='required')]}]}
2025-07-09 14:13:59,592 [WARNING] django.request: Bad Request: /api/user/create/
2025-07-09 14:13:59,593 [WARNING] django.server: "POST /api/user/create/ HTTP/1.1" 400 290
2025-07-09 14:25:20,258 [INFO] django.server: "GET /api/tenant/modules/ HTTP/1.1" 200 146
2025-07-09 14:25:20,394 [INFO] core: Listing tenants: [2] for tenant proliance
2025-07-09 14:25:20,397 [INFO] django.server: "GET /api/tenant/tenants/ HTTP/1.1" 200 365
2025-07-09 14:26:35,739 [ERROR] users: Validation error for tenant proliance: {'profile': [ErrorDetail(string='This field is required.', code='required')], 'modules': [ErrorDetail(string='Incorrect type. Expected pk value, received list.', code='incorrect_type')], 'documents': [{'title': [ErrorDetail(string='This field is required.', code='required')], 'file': [ErrorDetail(string='No file was submitted.', code='required')]}, {'title': [ErrorDetail(string='This field is required.', code='required')], 'file': [ErrorDetail(string='No file was submitted.', code='required')]}]}
2025-07-09 14:26:35,740 [WARNING] django.request: Bad Request: /api/user/create/
2025-07-09 14:26:35,741 [WARNING] django.server: "POST /api/user/create/ HTTP/1.1" 400 290
2025-07-09 14:29:59,201 [INFO] django.server: "GET /api/token/validate/ HTTP/1.1" 200 372
2025-07-09 14:30:08,953 [INFO] django.server: "GET /api/token/validate/ HTTP/1.1" 200 372
2025-07-09 14:30:09,119 [INFO] django.server: "GET /api/token/validate/ HTTP/1.1" 200 372
2025-07-09 14:34:50,842 [INFO] django.server: "GET /api/talent-engine/requisitions/ HTTP/1.1" 200 8696
2025-07-09 14:34:50,957 [INFO] django.server: "GET /api/talent-engine/requisitions/ HTTP/1.1" 200 8696
2025-07-09 14:35:38,521 [INFO] django.server: "GET /api/talent-engine/requisitions/ HTTP/1.1" 200 8696
2025-07-09 14:35:38,631 [INFO] django.server: "GET /api/talent-engine/requisitions/ HTTP/1.1" 200 8696
2025-07-09 14:36:28,542 [INFO] django.server: "GET /api/talent-engine/requisitions/ HTTP/1.1" 200 8696
2025-07-09 14:41:30,925 [INFO] django.server: "POST /api/token/ HTTP/1.1" 200 956
2025-07-09 14:41:30,977 [INFO] django.server: "OPTIONS /api/token/validate/ HTTP/1.1" 200 0
2025-07-09 14:41:30,983 [INFO] django.server: "OPTIONS /api/token/validate/ HTTP/1.1" 200 0
2025-07-09 14:41:31,170 [INFO] django.server: "GET /api/token/validate/ HTTP/1.1" 200 372
2025-07-09 14:41:31,266 [INFO] django.server: "GET /api/token/validate/ HTTP/1.1" 200 372
2025-07-09 14:43:41,717 [INFO] django.server: "GET /api/talent-engine/requisitions/ HTTP/1.1" 200 8696
2025-07-09 14:43:41,877 [INFO] django.server: "GET /api/talent-engine/requisitions/ HTTP/1.1" 200 8696
2025-07-09 14:43:47,367 [INFO] django.server: "GET /api/talent-engine/requisitions/ HTTP/1.1" 200 8696
2025-07-09 14:43:47,469 [INFO] django.server: "GET /api/talent-engine/requisitions/ HTTP/1.1" 200 8696
2025-07-09 14:43:48,718 [INFO] django.server: "GET /api/talent-engine/requisitions/ HTTP/1.1" 200 8696
2025-07-09 14:43:48,928 [INFO] django.server: "GET /api/talent-engine/requisitions/ HTTP/1.1" 200 8696
2025-07-09 14:43:50,621 [INFO] django.server: "OPTIONS /api/talent-engine-job-applications/published-requisitions-with-shortlisted/ HTTP/1.1" 200 0
2025-07-09 14:43:50,623 [INFO] django.server: "OPTIONS /api/talent-engine-job-applications/published-requisitions-with-shortlisted/ HTTP/1.1" 200 0
2025-07-09 14:43:50,738 [INFO] django.server: "GET /api/talent-engine-job-applications/published-requisitions-with-shortlisted/ HTTP/1.1" 200 10751
2025-07-09 14:43:50,829 [INFO] django.server: "GET /api/talent-engine-job-applications/published-requisitions-with-shortlisted/ HTTP/1.1" 200 10751
2025-07-09 14:43:50,920 [INFO] django.server: "GET /api/talent-engine-job-applications/published-requisitions-with-shortlisted/ HTTP/1.1" 200 10751
2025-07-09 14:43:51,015 [INFO] django.server: "GET /api/talent-engine-job-applications/published-requisitions-with-shortlisted/ HTTP/1.1" 200 10751
2025-07-09 14:48:36,281 [INFO] django.server: "GET /api/talent-engine-job-applications/published-requisitions-with-shortlisted/ HTTP/1.1" 200 10751
2025-07-09 14:48:36,431 [INFO] django.server: "GET /api/talent-engine-job-applications/published-requisitions-with-shortlisted/ HTTP/1.1" 200 10751
2025-07-09 14:48:36,583 [INFO] django.server: "GET /api/talent-engine-job-applications/published-requisitions-with-shortlisted/ HTTP/1.1" 200 10751
2025-07-09 14:48:54,354 [INFO] django.server: "GET /api/talent-engine-job-applications/published-requisitions-with-shortlisted/ HTTP/1.1" 200 10751
2025-07-09 14:48:54,559 [INFO] django.server: "GET /api/talent-engine-job-applications/published-requisitions-with-shortlisted/ HTTP/1.1" 200 10751
2025-07-09 14:48:54,754 [INFO] django.server: "GET /api/talent-engine-job-applications/published-requisitions-with-shortlisted/ HTTP/1.1" 200 10751
2025-07-09 14:51:33,952 [INFO] django.server: "GET /api/talent-engine-job-applications/published-requisitions-with-shortlisted/ HTTP/1.1" 200 10751
2025-07-09 14:51:34,056 [INFO] django.server: "GET /api/talent-engine-job-applications/published-requisitions-with-shortlisted/ HTTP/1.1" 200 10751
2025-07-09 14:51:35,283 [INFO] django.server: "OPTIONS /api/talent-engine-job-applications/schedules/ HTTP/1.1" 200 0
2025-07-09 14:51:35,285 [INFO] django.server: "OPTIONS /api/talent-engine-job-applications/schedules/ HTTP/1.1" 200 0
2025-07-09 14:51:35,408 [INFO] django.server: "GET /api/talent-engine-job-applications/schedules/ HTTP/1.1" 200 7513
2025-07-09 14:51:35,535 [INFO] django.server: "GET /api/talent-engine-job-applications/schedules/ HTTP/1.1" 200 7513
2025-07-09 14:51:47,358 [INFO] django.server: "GET /api/talent-engine-job-applications/applications/code/PR-JA-0001/email/john.adebayo@email.com/with-schedules/schedules/?unique_link=proliance-nlp-data-scientist-12a4a2fd HTTP/1.1" 200 6487
2025-07-09 14:51:47,499 [INFO] django.server: "GET /api/talent-engine-job-applications/applications/code/PR-JA-0001/email/john.adebayo@email.com/with-schedules/schedules/?unique_link=proliance-nlp-data-scientist-12a4a2fd HTTP/1.1" 200 6487
2025-07-09 14:55:35,369 [INFO] django.server: "GET /api/talent-engine-job-applications/applications/code/PR-JA-0001/email/john.adebayo@email.com/with-schedules/schedules/?unique_link=proliance-nlp-data-scientist-12a4a2fd HTTP/1.1" 200 6487
2025-07-09 14:55:40,425 [INFO] django.server: "GET /api/talent-engine-job-applications/applications/code/PR-JA-0001/email/john.adebayo@email.com/with-schedules/schedules/?unique_link=proliance-nlp-data-scientist-12a4a2fd HTTP/1.1" 200 6487
2025-07-09 14:55:40,648 [INFO] django.server: "GET /api/talent-engine-job-applications/applications/code/PR-JA-0001/email/john.adebayo@email.com/with-schedules/schedules/?unique_link=proliance-nlp-data-scientist-12a4a2fd HTTP/1.1" 200 6487
2025-07-09 14:56:21,085 [INFO] django.server: "GET /api/talent-engine-job-applications/applications/code/PR-JA-0001/email/john.adebayo@email.com/with-schedules/schedules/?unique_link=proliance-nlp-data-scientist-12a4a2fd HTTP/1.1" 200 6487
2025-07-09 14:57:29,348 [INFO] django.server: "GET /api/talent-engine/requisitions/ HTTP/1.1" 200 8696
2025-07-09 14:57:29,455 [INFO] django.server: "GET /api/talent-engine/requisitions/ HTTP/1.1" 200 8696
2025-07-09 14:58:20,228 [INFO] django.server: "GET /api/talent-engine/requisitions/ HTTP/1.1" 200 8696
2025-07-09 14:58:20,334 [INFO] django.server: "GET /api/talent-engine-job-applications/applications/code/PR-JA-0001/email/john.adebayo@email.com/with-schedules/schedules/?unique_link=proliance-nlp-data-scientist-12a4a2fd HTTP/1.1" 200 6487
2025-07-09 14:58:20,470 [INFO] django.server: "GET /api/talent-engine-job-applications/applications/code/PR-JA-0001/email/john.adebayo@email.com/with-schedules/schedules/?unique_link=proliance-nlp-data-scientist-12a4a2fd HTTP/1.1" 200 6487
2025-07-09 14:58:25,318 [INFO] django.server: "GET /api/talent-engine-job-applications/applications/code/PR-JA-0001/email/john.adebayo@email.com/with-schedules/schedules/?unique_link=proliance-nlp-data-scientist-12a4a2fd HTTP/1.1" 200 6487
2025-07-09 14:58:25,542 [INFO] django.server: "GET /api/talent-engine-job-applications/applications/code/PR-JA-0001/email/john.adebayo@email.com/with-schedules/schedules/?unique_link=proliance-nlp-data-scientist-12a4a2fd HTTP/1.1" 200 6487
2025-07-09 14:59:11,196 [INFO] django.server: "GET /api/talent-engine/requisitions/ HTTP/1.1" 200 8696
2025-07-09 15:00:02,206 [INFO] django.server: "GET /api/talent-engine/requisitions/ HTTP/1.1" 200 8696
2025-07-09 15:01:46,217 [INFO] django.server: "GET /api/token/validate/ HTTP/1.1" 200 372
2025-07-09 15:01:46,251 [INFO] django.server: "GET /api/talent-engine-job-applications/applications/code/PR-JA-0001/email/john.adebayo@email.com/with-schedules/schedules/?unique_link=proliance-nlp-data-scientist-12a4a2fd HTTP/1.1" 200 6487
2025-07-09 15:01:46,277 [INFO] django.server: "GET /api/talent-engine/requisitions/ HTTP/1.1" 200 8696
2025-07-09 15:01:56,058 [INFO] django.server: "GET /api/talent-engine-job-applications/applications/code/PR-JA-0001/email/john.adebayo@email.com/with-schedules/schedules/?unique_link=proliance-nlp-data-scientist-12a4a2fd HTTP/1.1" 200 6487
2025-07-09 15:01:56,414 [INFO] django.server: "GET /api/talent-engine-job-applications/applications/code/PR-JA-0001/email/john.adebayo@email.com/with-schedules/schedules/?unique_link=proliance-nlp-data-scientist-12a4a2fd HTTP/1.1" 200 6487
2025-07-09 15:01:57,415 [INFO] django.server: "GET /api/token/validate/ HTTP/1.1" 200 372
2025-07-09 15:01:57,619 [INFO] django.server: "GET /api/token/validate/ HTTP/1.1" 200 372
2025-07-09 15:01:57,684 [INFO] django.server: "GET /api/talent-engine/requisitions/ HTTP/1.1" 200 8696
2025-07-09 15:01:57,844 [INFO] django.server: "GET /api/talent-engine/requisitions/ HTTP/1.1" 200 8696
2025-07-09 15:02:48,255 [INFO] django.server: "GET /api/talent-engine/requisitions/ HTTP/1.1" 200 8696
2025-07-09 15:03:39,211 [INFO] django.server: "GET /api/talent-engine/requisitions/ HTTP/1.1" 200 8696
2025-07-09 15:04:30,187 [INFO] django.server: "GET /api/talent-engine/requisitions/ HTTP/1.1" 200 8696
2025-07-09 15:05:21,317 [INFO] django.server: "GET /api/talent-engine/requisitions/ HTTP/1.1" 200 8696
2025-07-09 15:06:12,193 [INFO] django.server: "GET /api/talent-engine/requisitions/ HTTP/1.1" 200 8696
2025-07-09 15:07:03,240 [INFO] django.server: "GET /api/talent-engine/requisitions/ HTTP/1.1" 200 8696
2025-07-09 15:07:54,200 [INFO] django.server: "GET /api/talent-engine/requisitions/ HTTP/1.1" 200 8696
2025-07-09 15:08:45,218 [INFO] django.server: "GET /api/talent-engine/requisitions/ HTTP/1.1" 200 8696
2025-07-09 15:09:36,213 [INFO] django.server: "GET /api/talent-engine/requisitions/ HTTP/1.1" 200 8696
2025-07-09 15:10:27,237 [INFO] django.server: "GET /api/talent-engine/requisitions/ HTTP/1.1" 200 8696
2025-07-09 15:11:18,246 [INFO] django.server: "GET /api/talent-engine/requisitions/ HTTP/1.1" 200 8696
2025-07-09 15:12:09,337 [INFO] django.server: "GET /api/talent-engine/requisitions/ HTTP/1.1" 200 8696
2025-07-09 15:13:00,261 [INFO] django.server: "GET /api/talent-engine/requisitions/ HTTP/1.1" 200 8696
2025-07-09 15:13:51,181 [INFO] django.server: "GET /api/talent-engine/requisitions/ HTTP/1.1" 200 8696
2025-07-09 15:14:42,201 [INFO] django.server: "GET /api/talent-engine/requisitions/ HTTP/1.1" 200 8696
2025-07-09 15:15:33,203 [INFO] django.server: "GET /api/talent-engine/requisitions/ HTTP/1.1" 200 8696
2025-07-09 15:16:24,225 [INFO] django.server: "GET /api/talent-engine/requisitions/ HTTP/1.1" 200 8696
2025-07-09 15:17:15,225 [INFO] django.server: "GET /api/talent-engine/requisitions/ HTTP/1.1" 200 8696
2025-07-09 15:18:06,262 [INFO] django.server: "GET /api/talent-engine/requisitions/ HTTP/1.1" 200 8696
2025-07-09 15:18:57,361 [INFO] django.server: "GET /api/talent-engine/requisitions/ HTTP/1.1" 200 8696
2025-07-09 15:19:48,180 [INFO] django.server: "GET /api/talent-engine/requisitions/ HTTP/1.1" 200 8696
2025-07-09 15:20:39,191 [INFO] django.server: "GET /api/talent-engine/requisitions/ HTTP/1.1" 200 8696
2025-07-09 15:21:30,457 [INFO] django.server: "GET /api/talent-engine/requisitions/ HTTP/1.1" 200 8696
2025-07-09 15:22:21,190 [INFO] django.server: "GET /api/talent-engine/requisitions/ HTTP/1.1" 200 8696
2025-07-09 15:23:12,288 [INFO] django.server: "GET /api/talent-engine/requisitions/ HTTP/1.1" 200 8696
2025-07-09 15:24:03,228 [INFO] django.server: "GET /api/talent-engine/requisitions/ HTTP/1.1" 200 8696
2025-07-09 15:24:54,203 [INFO] django.server: "GET /api/talent-engine/requisitions/ HTTP/1.1" 200 8696
2025-07-09 15:25:45,211 [INFO] django.server: "GET /api/talent-engine/requisitions/ HTTP/1.1" 200 8696
2025-07-09 15:26:36,228 [INFO] django.server: "GET /api/talent-engine/requisitions/ HTTP/1.1" 200 8696
2025-07-09 15:27:12,147 [INFO] django.server: "GET /api/talent-engine-job-applications/published-requisitions-with-shortlisted/ HTTP/1.1" 200 10751
2025-07-09 15:27:12,243 [INFO] django.server: "GET /api/talent-engine-job-applications/published-requisitions-with-shortlisted/ HTTP/1.1" 200 10751
2025-07-09 15:27:12,337 [INFO] django.server: "GET /api/talent-engine-job-applications/published-requisitions-with-shortlisted/ HTTP/1.1" 200 10751
2025-07-09 15:27:12,440 [INFO] django.server: "GET /api/talent-engine-job-applications/published-requisitions-with-shortlisted/ HTTP/1.1" 200 10751
2025-07-09 15:28:09,872 [INFO] django.server: "GET /api/talent-engine-job-applications/applications/code/PR-JA-0001/email/john.adebayo@email.com/with-schedules/schedules/?unique_link=proliance-nlp-data-scientist-12a4a2fd HTTP/1.1" 200 6487
2025-07-09 15:28:10,008 [INFO] django.server: "GET /api/talent-engine-job-applications/applications/code/PR-JA-0001/email/john.adebayo@email.com/with-schedules/schedules/?unique_link=proliance-nlp-data-scientist-12a4a2fd HTTP/1.1" 200 6487
2025-07-10 08:19:21,953 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2025-07-10 08:20:57,209 [INFO] django.server: "OPTIONS /api/token/ HTTP/1.1" 200 0
2025-07-10 08:21:01,021 [INFO] django.server: "POST /api/token/ HTTP/1.1" 200 931
2025-07-10 08:21:01,097 [INFO] django.server: "OPTIONS /api/token/validate/ HTTP/1.1" 200 0
2025-07-10 08:21:01,104 [INFO] django.server: "OPTIONS /api/token/validate/ HTTP/1.1" 200 0
2025-07-10 08:21:01,306 [INFO] django.server: "GET /api/token/validate/ HTTP/1.1" 200 366
2025-07-10 08:21:01,306 [INFO] django.server: "GET /api/token/validate/ HTTP/1.1" 200 366
2025-07-10 08:22:27,736 [INFO] django.server: "OPTIONS /api/talent-engine/requisitions/ HTTP/1.1" 200 0
2025-07-10 08:22:27,736 [INFO] django.server: "OPTIONS /api/talent-engine/requisitions/ HTTP/1.1" 200 0
2025-07-10 08:22:28,015 [WARNING] django.request: Forbidden: /api/talent-engine/requisitions/
2025-07-10 08:22:28,015 [WARNING] django.request: Forbidden: /api/talent-engine/requisitions/
2025-07-10 08:22:28,017 [WARNING] django.server: "GET /api/talent-engine/requisitions/ HTTP/1.1" 403 63
2025-07-10 08:22:28,018 [WARNING] django.server: "GET /api/talent-engine/requisitions/ HTTP/1.1" 403 63
2025-07-10 08:23:12,284 [INFO] django.server: "POST /api/token/ HTTP/1.1" 200 956
2025-07-10 08:23:12,496 [INFO] django.server: "GET /api/token/validate/ HTTP/1.1" 200 372
2025-07-10 08:23:12,514 [INFO] django.server: "GET /api/token/validate/ HTTP/1.1" 200 372
2025-07-10 08:23:33,786 [INFO] django.server: "GET /api/talent-engine/requisitions/ HTTP/1.1" 200 8696
2025-07-10 08:23:33,786 [INFO] django.server: "GET /api/talent-engine/requisitions/ HTTP/1.1" 200 8696
2025-07-10 08:24:16,169 [INFO] django.utils.autoreload: C:\Users\CPT-003\Desktop\CRM\crm_api\talent_engine\models.py changed, reloading.
2025-07-10 08:24:22,100 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2025-07-10 08:24:51,302 [INFO] django.server: "POST /api/token/ HTTP/1.1" 200 956
2025-07-10 08:25:15,557 [INFO] django.server: "GET /api/talent-engine/requisitions/ HTTP/1.1" 200 8696
2025-07-10 08:26:06,520 [INFO] django.server: "GET /api/talent-engine/requisitions/ HTTP/1.1" 200 8696
2025-07-10 08:26:09,037 [INFO] django.server: "GET /api/talent-engine/requisitions/ HTTP/1.1" 200 8696
2025-07-10 08:26:57,532 [INFO] django.server: "GET /api/talent-engine/requisitions/ HTTP/1.1" 200 8696
2025-07-10 08:27:29,841 [INFO] django.server: "POST /api/token/ HTTP/1.1" 200 953
2025-07-10 08:27:48,496 [INFO] django.server: "GET /api/talent-engine/requisitions/ HTTP/1.1" 200 8696
2025-07-10 08:27:48,620 [INFO] django.server: "GET /api/talent-engine/requisitions/ HTTP/1.1" 200 8696
2025-07-10 08:28:17,153 [ERROR] django.request: Internal Server Error: /api/talent-engine/requisitions/
Traceback (most recent call last):
  File "C:\Users\CPT-003\Desktop\CRM\crm_api\venv\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
psycopg2.errors.UndefinedTable: relation "talent_engine_job_requisition" does not exist
LINE 1: SELECT 1 AS "a" FROM "talent_engine_job_requisition" WHERE "...
                             ^


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\CPT-003\Desktop\CRM\crm_api\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\CPT-003\Desktop\CRM\crm_api\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\CPT-003\Desktop\CRM\crm_api\venv\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "C:\Users\CPT-003\Desktop\CRM\crm_api\venv\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\CPT-003\Desktop\CRM\crm_api\venv\Lib\site-packages\rest_framework\views.py", line 515, in dispatch
    response = self.handle_exception(exc)
  File "C:\Users\CPT-003\Desktop\CRM\crm_api\venv\Lib\site-packages\rest_framework\views.py", line 475, in handle_exception
    self.raise_uncaught_exception(exc)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^
  File "C:\Users\CPT-003\Desktop\CRM\crm_api\venv\Lib\site-packages\rest_framework\views.py", line 486, in raise_uncaught_exception
    raise exc
  File "C:\Users\CPT-003\Desktop\CRM\crm_api\venv\Lib\site-packages\rest_framework\views.py", line 512, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\Users\CPT-003\Desktop\CRM\crm_api\venv\Lib\site-packages\rest_framework\generics.py", line 246, in post
    return self.create(request, *args, **kwargs)
           ~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\CPT-003\Desktop\CRM\crm_api\venv\Lib\site-packages\rest_framework\mixins.py", line 18, in create
    serializer.is_valid(raise_exception=True)
    ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\CPT-003\Desktop\CRM\crm_api\venv\Lib\site-packages\rest_framework\serializers.py", line 225, in is_valid
    self._validated_data = self.run_validation(self.initial_data)
                           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^
  File "C:\Users\CPT-003\Desktop\CRM\crm_api\venv\Lib\site-packages\rest_framework\serializers.py", line 444, in run_validation
    value = self.to_internal_value(data)
  File "C:\Users\CPT-003\Desktop\CRM\crm_api\venv\Lib\site-packages\rest_framework\serializers.py", line 501, in to_internal_value
    validated_value = field.run_validation(primitive_value)
  File "C:\Users\CPT-003\Desktop\CRM\crm_api\venv\Lib\site-packages\rest_framework\fields.py", line 757, in run_validation
    return super().run_validation(data)
           ~~~~~~~~~~~~~~~~~~~~~~^^^^^^
  File "C:\Users\CPT-003\Desktop\CRM\crm_api\venv\Lib\site-packages\rest_framework\fields.py", line 539, in run_validation
    self.run_validators(value)
    ~~~~~~~~~~~~~~~~~~~^^^^^^^
  File "C:\Users\CPT-003\Desktop\CRM\crm_api\venv\Lib\site-packages\rest_framework\fields.py", line 551, in run_validators
    validator(value, self)
    ~~~~~~~~~^^^^^^^^^^^^^
  File "C:\Users\CPT-003\Desktop\CRM\crm_api\venv\Lib\site-packages\rest_framework\validators.py", line 86, in __call__
    if qs_exists(queryset):
       ~~~~~~~~~^^^^^^^^^^
  File "C:\Users\CPT-003\Desktop\CRM\crm_api\venv\Lib\site-packages\rest_framework\validators.py", line 23, in qs_exists
    return queryset.exists()
           ~~~~~~~~~~~~~~~^^
  File "C:\Users\CPT-003\Desktop\CRM\crm_api\venv\Lib\site-packages\django\db\models\query.py", line 1296, in exists
    return self.query.has_results(using=self.db)
           ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "C:\Users\CPT-003\Desktop\CRM\crm_api\venv\Lib\site-packages\django\db\models\sql\query.py", line 674, in has_results
    return compiler.has_results()
           ~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\CPT-003\Desktop\CRM\crm_api\venv\Lib\site-packages\django\db\models\sql\compiler.py", line 1591, in has_results
    return bool(self.execute_sql(SINGLE))
                ~~~~~~~~~~~~~~~~^^^^^^^^
  File "C:\Users\CPT-003\Desktop\CRM\crm_api\venv\Lib\site-packages\django\db\models\sql\compiler.py", line 1623, in execute_sql
    cursor.execute(sql, params)
    ~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\Users\CPT-003\Desktop\CRM\crm_api\venv\Lib\site-packages\django\db\backends\utils.py", line 122, in execute
    return super().execute(sql, params)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\Users\CPT-003\Desktop\CRM\crm_api\venv\Lib\site-packages\django\db\backends\utils.py", line 79, in execute
    return self._execute_with_wrappers(
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        sql, params, many=False, executor=self._execute
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\CPT-003\Desktop\CRM\crm_api\venv\Lib\site-packages\django\db\backends\utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "C:\Users\CPT-003\Desktop\CRM\crm_api\venv\Lib\site-packages\django\db\backends\utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\CPT-003\Desktop\CRM\crm_api\venv\Lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\Users\CPT-003\Desktop\CRM\crm_api\venv\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
django.db.utils.ProgrammingError: relation "talent_engine_job_requisition" does not exist
LINE 1: SELECT 1 AS "a" FROM "talent_engine_job_requisition" WHERE "...
                             ^

2025-07-10 08:28:17,172 [ERROR] django.server: "POST /api/talent-engine/requisitions/ HTTP/1.1" 500 234926
2025-07-10 08:28:39,524 [INFO] django.server: "GET /api/talent-engine/requisitions/ HTTP/1.1" 200 8696
2025-07-10 08:29:30,558 [INFO] django.server: "GET /api/talent-engine/requisitions/ HTTP/1.1" 200 8696
2025-07-10 08:33:08,396 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2025-07-10 08:33:27,079 [WARNING] django.request: Bad Request: /api/talent-engine/requisitions/
2025-07-10 08:33:27,080 [WARNING] django.server: "POST /api/talent-engine/requisitions/ HTTP/1.1" 400 37
2025-07-10 08:33:45,525 [INFO] django.server: "GET /api/talent-engine/requisitions/ HTTP/1.1" 200 8696
2025-07-10 08:33:55,140 [INFO] django.server: "POST /api/talent-engine/requisitions/ HTTP/1.1" 201 2123
2025-07-10 08:34:36,538 [INFO] django.server: "GET /api/talent-engine/requisitions/ HTTP/1.1" 200 10820
2025-07-10 08:35:27,627 [INFO] django.server: "GET /api/talent-engine/requisitions/ HTTP/1.1" 200 10820
2025-07-10 08:36:18,544 [INFO] django.server: "GET /api/talent-engine/requisitions/ HTTP/1.1" 200 10820
2025-07-10 08:37:09,819 [INFO] django.server: "GET /api/talent-engine/requisitions/ HTTP/1.1" 200 10820
2025-07-10 08:38:00,577 [INFO] django.server: "GET /api/talent-engine/requisitions/ HTTP/1.1" 200 10820
2025-07-10 08:38:07,304 [INFO] django.utils.autoreload: C:\Users\CPT-003\Desktop\CRM\crm_api\talent_engine\views.py changed, reloading.
2025-07-10 08:38:13,261 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2025-07-10 08:38:51,646 [INFO] django.server: "GET /api/talent-engine/requisitions/ HTTP/1.1" 200 10820
2025-07-10 08:39:07,810 [INFO] django.utils.autoreload: C:\Users\CPT-003\Desktop\CRM\crm_api\talent_engine\views.py changed, reloading.
2025-07-10 08:39:12,589 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2025-07-10 08:39:42,669 [INFO] django.server: "GET /api/talent-engine/requisitions/ HTTP/1.1" 200 10820
2025-07-10 08:39:53,967 [INFO] django.utils.autoreload: C:\Users\CPT-003\Desktop\CRM\crm_api\users\views.py changed, reloading.
2025-07-10 08:39:58,391 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2025-07-10 08:40:33,665 [INFO] django.server: "GET /api/talent-engine/requisitions/ HTTP/1.1" 200 10820
2025-07-10 08:40:46,322 [INFO] django.server: "POST /api/talent-engine/requisitions/ HTTP/1.1" 201 1826
2025-07-10 08:41:24,599 [INFO] django.server: "GET /api/talent-engine/requisitions/ HTTP/1.1" 200 12647
2025-07-10 08:41:47,287 [INFO] django.utils.autoreload: C:\Users\CPT-003\Desktop\CRM\crm_api\lumina_care\settings.py changed, reloading.
2025-07-10 08:41:52,560 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2025-07-10 08:42:32,323 [INFO] django.server: "GET /api/talent-engine/requisitions/ HTTP/1.1" 200 11697
2025-07-10 08:43:23,241 [INFO] django.server: "GET /api/talent-engine/requisitions/ HTTP/1.1" 200 11697
2025-07-10 08:44:14,244 [INFO] django.server: "GET /api/talent-engine/requisitions/ HTTP/1.1" 200 11697
2025-07-10 08:45:05,026 [INFO] django.server: "GET /api/talent-engine/requisitions/ HTTP/1.1" 200 11697
2025-07-10 08:45:56,106 [INFO] django.server: "GET /api/talent-engine/requisitions/ HTTP/1.1" 200 11697
2025-07-10 08:46:47,638 [INFO] django.server: "GET /api/talent-engine/requisitions/ HTTP/1.1" 200 11697
2025-07-10 08:47:38,730 [INFO] django.server: "GET /api/talent-engine/requisitions/ HTTP/1.1" 200 11697
2025-07-10 08:48:29,315 [INFO] django.server: "GET /api/talent-engine/requisitions/ HTTP/1.1" 200 11697
2025-07-10 08:49:20,623 [INFO] django.server: "GET /api/talent-engine/requisitions/ HTTP/1.1" 200 11697
2025-07-10 08:50:12,023 [INFO] django.server: "GET /api/talent-engine/requisitions/ HTTP/1.1" 200 11697
2025-07-10 08:51:03,329 [INFO] django.server: "GET /api/talent-engine/requisitions/ HTTP/1.1" 200 11697
2025-07-10 08:51:53,196 [INFO] django.server: "GET /api/talent-engine/requisitions/ HTTP/1.1" 200 11697
2025-07-10 08:51:53,578 [INFO] django.utils.autoreload: C:\Users\CPT-003\Desktop\CRM\crm_api\lumina_care\settings.py changed, reloading.
2025-07-10 08:51:59,013 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2025-07-10 08:52:27,755 [INFO] django.server: "GET /api/talent-engine/requisitions/ HTTP/1.1" 200 12647
2025-07-10 08:53:18,581 [INFO] django.server: "GET /api/talent-engine/requisitions/ HTTP/1.1" 200 12647
2025-07-10 08:54:09,557 [INFO] django.server: "GET /api/talent-engine/requisitions/ HTTP/1.1" 200 12647
2025-07-10 08:54:53,903 [INFO] django.utils.autoreload: C:\Users\CPT-003\Desktop\CRM\crm_api\lumina_care\settings.py changed, reloading.
2025-07-10 08:54:59,268 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2025-07-10 08:56:07,639 [INFO] django.server: "GET /api/talent-engine/requisitions/ HTTP/1.1" 200 11697
2025-07-10 08:56:57,222 [INFO] django.server: "GET /api/talent-engine/requisitions/ HTTP/1.1" 200 11697
2025-07-10 08:57:00,917 [INFO] django.utils.autoreload: C:\Users\CPT-003\Desktop\CRM\crm_api\lumina_care\settings.py changed, reloading.
2025-07-10 08:57:05,344 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2025-07-10 08:57:32,538 [INFO] django.server: "GET /api/talent-engine/requisitions/ HTTP/1.1" 200 12647
2025-07-10 08:58:23,511 [INFO] django.server: "GET /api/talent-engine/requisitions/ HTTP/1.1" 200 12647
2025-07-10 09:08:07,373 [INFO] django.server: "GET /api/talent-engine/requisitions/ HTTP/1.1" 200 12647
2025-07-10 09:08:07,528 [INFO] django.server: "GET /api/talent-engine/requisitions/ HTTP/1.1" 200 12647
2025-07-10 09:16:48,245 [INFO] django.utils.autoreload: C:\Users\CPT-003\Desktop\CRM\crm_api\core\models.py changed, reloading.
2025-07-10 09:16:51,299 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2025-07-10 09:17:38,637 [INFO] django.utils.autoreload: C:\Users\CPT-003\Desktop\CRM\crm_api\core\serializers.py changed, reloading.
2025-07-10 09:17:41,827 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2025-07-10 09:18:30,441 [INFO] django.utils.autoreload: C:\Users\CPT-003\Desktop\CRM\crm_api\core\serializers.py changed, reloading.
2025-07-10 09:18:33,378 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2025-07-10 09:19:12,706 [INFO] django.utils.autoreload: C:\Users\CPT-003\Desktop\CRM\crm_api\core\views.py changed, reloading.
2025-07-10 09:19:15,126 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2025-07-10 09:20:42,163 [INFO] django.utils.autoreload: C:\Users\CPT-003\Desktop\CRM\crm_api\core\urls.py changed, reloading.
2025-07-10 09:20:44,899 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2025-07-10 09:24:59,347 [INFO] django.server: "OPTIONS /api/config/ HTTP/1.1" 200 0
2025-07-10 09:24:59,351 [INFO] django.server: "OPTIONS /api/config/ HTTP/1.1" 200 0
2025-07-10 09:24:59,522 [WARNING] django.request: Not Found: /api/config/
2025-07-10 09:24:59,522 [WARNING] django.request: Not Found: /api/config/
2025-07-10 09:24:59,523 [WARNING] django.server: "GET /api/config/ HTTP/1.1" 404 4417
2025-07-10 09:24:59,524 [WARNING] django.server: "GET /api/config/ HTTP/1.1" 404 4417
2025-07-10 09:25:33,218 [ERROR] django.request: Internal Server Error: /api/tenant/tenants/
Traceback (most recent call last):
  File "C:\Users\CPT-003\Desktop\CRM\crm_api\venv\Lib\site-packages\django\db\models\fields\related_descriptors.py", line 516, in __get__
    rel_obj = self.related.get_cached_value(instance)
  File "C:\Users\CPT-003\Desktop\CRM\crm_api\venv\Lib\site-packages\django\db\models\fields\mixins.py", line 37, in get_cached_value
    return instance._state.fields_cache[self.cache_name]
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
KeyError: 'tenantconfig'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\CPT-003\Desktop\CRM\crm_api\venv\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
psycopg2.errors.UndefinedColumn: column core_tenantconfig.email_templates does not exist
LINE 1: ...fig"."logo", "core_tenantconfig"."custom_fields", "core_tena...
                                                             ^


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\CPT-003\Desktop\CRM\crm_api\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\CPT-003\Desktop\CRM\crm_api\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\CPT-003\Desktop\CRM\crm_api\venv\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "C:\Users\CPT-003\Desktop\CRM\crm_api\venv\Lib\site-packages\rest_framework\viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
           ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\CPT-003\Desktop\CRM\crm_api\venv\Lib\site-packages\rest_framework\views.py", line 515, in dispatch
    response = self.handle_exception(exc)
  File "C:\Users\CPT-003\Desktop\CRM\crm_api\venv\Lib\site-packages\rest_framework\views.py", line 475, in handle_exception
    self.raise_uncaught_exception(exc)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^
  File "C:\Users\CPT-003\Desktop\CRM\crm_api\venv\Lib\site-packages\rest_framework\views.py", line 486, in raise_uncaught_exception
    raise exc
  File "C:\Users\CPT-003\Desktop\CRM\crm_api\venv\Lib\site-packages\rest_framework\views.py", line 512, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\Users\CPT-003\Desktop\CRM\crm_api\core\views.py", line 286, in list
    logger.info(f"Listing tenants: {[t['id'] for t in serializer.data]} for tenant {request.tenant.schema_name}")
                                                      ^^^^^^^^^^^^^^^
  File "C:\Users\CPT-003\Desktop\CRM\crm_api\venv\Lib\site-packages\rest_framework\serializers.py", line 797, in data
    ret = super().data
          ^^^^^^^^^^^^
  File "C:\Users\CPT-003\Desktop\CRM\crm_api\venv\Lib\site-packages\rest_framework\serializers.py", line 251, in data
    self._data = self.to_representation(self.instance)
                 ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "C:\Users\CPT-003\Desktop\CRM\crm_api\venv\Lib\site-packages\rest_framework\serializers.py", line 716, in to_representation
    self.child.to_representation(item) for item in iterable
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^
  File "C:\Users\CPT-003\Desktop\CRM\crm_api\venv\Lib\site-packages\rest_framework\serializers.py", line 527, in to_representation
    attribute = field.get_attribute(instance)
  File "C:\Users\CPT-003\Desktop\CRM\crm_api\venv\Lib\site-packages\rest_framework\fields.py", line 437, in get_attribute
    return get_attribute(instance, self.source_attrs)
  File "C:\Users\CPT-003\Desktop\CRM\crm_api\venv\Lib\site-packages\rest_framework\fields.py", line 104, in get_attribute
    instance = getattr(instance, attr)
  File "C:\Users\CPT-003\Desktop\CRM\crm_api\venv\Lib\site-packages\django\db\models\fields\related_descriptors.py", line 523, in __get__
    rel_obj = self.get_queryset(instance=instance).get(**filter_args)
  File "C:\Users\CPT-003\Desktop\CRM\crm_api\venv\Lib\site-packages\django\db\models\query.py", line 629, in get
    num = len(clone)
  File "C:\Users\CPT-003\Desktop\CRM\crm_api\venv\Lib\site-packages\django\db\models\query.py", line 366, in __len__
    self._fetch_all()
    ~~~~~~~~~~~~~~~^^
  File "C:\Users\CPT-003\Desktop\CRM\crm_api\venv\Lib\site-packages\django\db\models\query.py", line 1949, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
                         ~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\CPT-003\Desktop\CRM\crm_api\venv\Lib\site-packages\django\db\models\query.py", line 91, in __iter__
    results = compiler.execute_sql(
        chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size
    )
  File "C:\Users\CPT-003\Desktop\CRM\crm_api\venv\Lib\site-packages\django\db\models\sql\compiler.py", line 1623, in execute_sql
    cursor.execute(sql, params)
    ~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\Users\CPT-003\Desktop\CRM\crm_api\venv\Lib\site-packages\django\db\backends\utils.py", line 122, in execute
    return super().execute(sql, params)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\Users\CPT-003\Desktop\CRM\crm_api\venv\Lib\site-packages\django\db\backends\utils.py", line 79, in execute
    return self._execute_with_wrappers(
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        sql, params, many=False, executor=self._execute
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\CPT-003\Desktop\CRM\crm_api\venv\Lib\site-packages\django\db\backends\utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "C:\Users\CPT-003\Desktop\CRM\crm_api\venv\Lib\site-packages\django\db\backends\utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\CPT-003\Desktop\CRM\crm_api\venv\Lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\Users\CPT-003\Desktop\CRM\crm_api\venv\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
django.db.utils.ProgrammingError: column core_tenantconfig.email_templates does not exist
LINE 1: ...fig"."logo", "core_tenantconfig"."custom_fields", "core_tena...
                                                             ^

2025-07-10 09:25:33,228 [ERROR] django.server: "GET /api/tenant/tenants/ HTTP/1.1" 500 217060
2025-07-10 09:25:51,399 [WARNING] django.request: Not Found: /api/config/
2025-07-10 09:25:51,400 [WARNING] django.server: "GET /api/config/ HTTP/1.1" 404 4417
2025-07-10 09:26:06,401 [WARNING] django.request: Not Found: /api/config/
2025-07-10 09:26:06,401 [WARNING] django.server: "GET /api/config/ HTTP/1.1" 404 4417
2025-07-10 09:26:34,334 [INFO] django.server: "OPTIONS /api/tenant/config/ HTTP/1.1" 200 0
2025-07-10 09:26:34,489 [ERROR] django.request: Internal Server Error: /api/tenant/config/
Traceback (most recent call last):
  File "C:\Users\CPT-003\Desktop\CRM\crm_api\venv\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
psycopg2.errors.UndefinedColumn: column core_tenantconfig.email_templates does not exist
LINE 1: ...fig"."logo", "core_tenantconfig"."custom_fields", "core_tena...
                                                             ^


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\CPT-003\Desktop\CRM\crm_api\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\CPT-003\Desktop\CRM\crm_api\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\CPT-003\Desktop\CRM\crm_api\venv\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "C:\Users\CPT-003\Desktop\CRM\crm_api\venv\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\CPT-003\Desktop\CRM\crm_api\venv\Lib\site-packages\rest_framework\views.py", line 515, in dispatch
    response = self.handle_exception(exc)
  File "C:\Users\CPT-003\Desktop\CRM\crm_api\venv\Lib\site-packages\rest_framework\views.py", line 475, in handle_exception
    self.raise_uncaught_exception(exc)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^
  File "C:\Users\CPT-003\Desktop\CRM\crm_api\venv\Lib\site-packages\rest_framework\views.py", line 486, in raise_uncaught_exception
    raise exc
  File "C:\Users\CPT-003\Desktop\CRM\crm_api\venv\Lib\site-packages\rest_framework\views.py", line 512, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\Users\CPT-003\Desktop\CRM\crm_api\core\views.py", line 202, in get
    config = TenantConfig.objects.get(tenant=tenant)
  File "C:\Users\CPT-003\Desktop\CRM\crm_api\venv\Lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "C:\Users\CPT-003\Desktop\CRM\crm_api\venv\Lib\site-packages\django\db\models\query.py", line 629, in get
    num = len(clone)
  File "C:\Users\CPT-003\Desktop\CRM\crm_api\venv\Lib\site-packages\django\db\models\query.py", line 366, in __len__
    self._fetch_all()
    ~~~~~~~~~~~~~~~^^
  File "C:\Users\CPT-003\Desktop\CRM\crm_api\venv\Lib\site-packages\django\db\models\query.py", line 1949, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
                         ~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\CPT-003\Desktop\CRM\crm_api\venv\Lib\site-packages\django\db\models\query.py", line 91, in __iter__
    results = compiler.execute_sql(
        chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size
    )
  File "C:\Users\CPT-003\Desktop\CRM\crm_api\venv\Lib\site-packages\django\db\models\sql\compiler.py", line 1623, in execute_sql
    cursor.execute(sql, params)
    ~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\Users\CPT-003\Desktop\CRM\crm_api\venv\Lib\site-packages\django\db\backends\utils.py", line 122, in execute
    return super().execute(sql, params)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\Users\CPT-003\Desktop\CRM\crm_api\venv\Lib\site-packages\django\db\backends\utils.py", line 79, in execute
    return self._execute_with_wrappers(
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        sql, params, many=False, executor=self._execute
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\CPT-003\Desktop\CRM\crm_api\venv\Lib\site-packages\django\db\backends\utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "C:\Users\CPT-003\Desktop\CRM\crm_api\venv\Lib\site-packages\django\db\backends\utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\CPT-003\Desktop\CRM\crm_api\venv\Lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\Users\CPT-003\Desktop\CRM\crm_api\venv\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
django.db.utils.ProgrammingError: column core_tenantconfig.email_templates does not exist
LINE 1: ...fig"."logo", "core_tenantconfig"."custom_fields", "core_tena...
                                                             ^

2025-07-10 09:26:34,496 [ERROR] django.server: "GET /api/tenant/config/ HTTP/1.1" 500 172898
2025-07-10 09:31:03,638 [ERROR] django.request: Internal Server Error: /api/tenant/config/
Traceback (most recent call last):
  File "C:\Users\CPT-003\Desktop\CRM\crm_api\venv\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
psycopg2.errors.UndefinedColumn: column core_tenantconfig.email_templates does not exist
LINE 1: ...fig"."logo", "core_tenantconfig"."custom_fields", "core_tena...
                                                             ^


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\CPT-003\Desktop\CRM\crm_api\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\CPT-003\Desktop\CRM\crm_api\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\CPT-003\Desktop\CRM\crm_api\venv\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "C:\Users\CPT-003\Desktop\CRM\crm_api\venv\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\CPT-003\Desktop\CRM\crm_api\venv\Lib\site-packages\rest_framework\views.py", line 515, in dispatch
    response = self.handle_exception(exc)
  File "C:\Users\CPT-003\Desktop\CRM\crm_api\venv\Lib\site-packages\rest_framework\views.py", line 475, in handle_exception
    self.raise_uncaught_exception(exc)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^
  File "C:\Users\CPT-003\Desktop\CRM\crm_api\venv\Lib\site-packages\rest_framework\views.py", line 486, in raise_uncaught_exception
    raise exc
  File "C:\Users\CPT-003\Desktop\CRM\crm_api\venv\Lib\site-packages\rest_framework\views.py", line 512, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\Users\CPT-003\Desktop\CRM\crm_api\core\views.py", line 202, in get
    config = TenantConfig.objects.get(tenant=tenant)
  File "C:\Users\CPT-003\Desktop\CRM\crm_api\venv\Lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "C:\Users\CPT-003\Desktop\CRM\crm_api\venv\Lib\site-packages\django\db\models\query.py", line 629, in get
    num = len(clone)
  File "C:\Users\CPT-003\Desktop\CRM\crm_api\venv\Lib\site-packages\django\db\models\query.py", line 366, in __len__
    self._fetch_all()
    ~~~~~~~~~~~~~~~^^
  File "C:\Users\CPT-003\Desktop\CRM\crm_api\venv\Lib\site-packages\django\db\models\query.py", line 1949, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
                         ~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\CPT-003\Desktop\CRM\crm_api\venv\Lib\site-packages\django\db\models\query.py", line 91, in __iter__
    results = compiler.execute_sql(
        chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size
    )
  File "C:\Users\CPT-003\Desktop\CRM\crm_api\venv\Lib\site-packages\django\db\models\sql\compiler.py", line 1623, in execute_sql
    cursor.execute(sql, params)
    ~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\Users\CPT-003\Desktop\CRM\crm_api\venv\Lib\site-packages\django\db\backends\utils.py", line 122, in execute
    return super().execute(sql, params)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\Users\CPT-003\Desktop\CRM\crm_api\venv\Lib\site-packages\django\db\backends\utils.py", line 79, in execute
    return self._execute_with_wrappers(
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        sql, params, many=False, executor=self._execute
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\CPT-003\Desktop\CRM\crm_api\venv\Lib\site-packages\django\db\backends\utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "C:\Users\CPT-003\Desktop\CRM\crm_api\venv\Lib\site-packages\django\db\backends\utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\CPT-003\Desktop\CRM\crm_api\venv\Lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\Users\CPT-003\Desktop\CRM\crm_api\venv\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
django.db.utils.ProgrammingError: column core_tenantconfig.email_templates does not exist
LINE 1: ...fig"."logo", "core_tenantconfig"."custom_fields", "core_tena...
                                                             ^

2025-07-10 09:31:03,645 [ERROR] django.request: Internal Server Error: /api/tenant/config/
Traceback (most recent call last):
  File "C:\Users\CPT-003\Desktop\CRM\crm_api\venv\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
psycopg2.errors.UndefinedColumn: column core_tenantconfig.email_templates does not exist
LINE 1: ...fig"."logo", "core_tenantconfig"."custom_fields", "core_tena...
                                                             ^


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\CPT-003\Desktop\CRM\crm_api\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\CPT-003\Desktop\CRM\crm_api\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\CPT-003\Desktop\CRM\crm_api\venv\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "C:\Users\CPT-003\Desktop\CRM\crm_api\venv\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\CPT-003\Desktop\CRM\crm_api\venv\Lib\site-packages\rest_framework\views.py", line 515, in dispatch
    response = self.handle_exception(exc)
  File "C:\Users\CPT-003\Desktop\CRM\crm_api\venv\Lib\site-packages\rest_framework\views.py", line 475, in handle_exception
    self.raise_uncaught_exception(exc)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^
  File "C:\Users\CPT-003\Desktop\CRM\crm_api\venv\Lib\site-packages\rest_framework\views.py", line 486, in raise_uncaught_exception
    raise exc
  File "C:\Users\CPT-003\Desktop\CRM\crm_api\venv\Lib\site-packages\rest_framework\views.py", line 512, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\Users\CPT-003\Desktop\CRM\crm_api\core\views.py", line 202, in get
    config = TenantConfig.objects.get(tenant=tenant)
  File "C:\Users\CPT-003\Desktop\CRM\crm_api\venv\Lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "C:\Users\CPT-003\Desktop\CRM\crm_api\venv\Lib\site-packages\django\db\models\query.py", line 629, in get
    num = len(clone)
  File "C:\Users\CPT-003\Desktop\CRM\crm_api\venv\Lib\site-packages\django\db\models\query.py", line 366, in __len__
    self._fetch_all()
    ~~~~~~~~~~~~~~~^^
  File "C:\Users\CPT-003\Desktop\CRM\crm_api\venv\Lib\site-packages\django\db\models\query.py", line 1949, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
                         ~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\CPT-003\Desktop\CRM\crm_api\venv\Lib\site-packages\django\db\models\query.py", line 91, in __iter__
    results = compiler.execute_sql(
        chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size
    )
  File "C:\Users\CPT-003\Desktop\CRM\crm_api\venv\Lib\site-packages\django\db\models\sql\compiler.py", line 1623, in execute_sql
    cursor.execute(sql, params)
    ~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\Users\CPT-003\Desktop\CRM\crm_api\venv\Lib\site-packages\django\db\backends\utils.py", line 122, in execute
    return super().execute(sql, params)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\Users\CPT-003\Desktop\CRM\crm_api\venv\Lib\site-packages\django\db\backends\utils.py", line 79, in execute
    return self._execute_with_wrappers(
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        sql, params, many=False, executor=self._execute
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\CPT-003\Desktop\CRM\crm_api\venv\Lib\site-packages\django\db\backends\utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "C:\Users\CPT-003\Desktop\CRM\crm_api\venv\Lib\site-packages\django\db\backends\utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\CPT-003\Desktop\CRM\crm_api\venv\Lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\Users\CPT-003\Desktop\CRM\crm_api\venv\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
django.db.utils.ProgrammingError: column core_tenantconfig.email_templates does not exist
LINE 1: ...fig"."logo", "core_tenantconfig"."custom_fields", "core_tena...
                                                             ^

2025-07-10 09:31:03,651 [ERROR] django.server: "GET /api/tenant/config/ HTTP/1.1" 500 172898
2025-07-10 09:31:03,654 [ERROR] django.server: "GET /api/tenant/config/ HTTP/1.1" 500 172898
2025-07-10 09:34:30,510 [ERROR] django.request: Internal Server Error: /api/tenant/config/
Traceback (most recent call last):
  File "C:\Users\CPT-003\Desktop\CRM\crm_api\venv\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
psycopg2.errors.UndefinedColumn: column core_tenantconfig.email_templates does not exist
LINE 1: ...fig"."logo", "core_tenantconfig"."custom_fields", "core_tena...
                                                             ^


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\CPT-003\Desktop\CRM\crm_api\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\CPT-003\Desktop\CRM\crm_api\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\CPT-003\Desktop\CRM\crm_api\venv\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "C:\Users\CPT-003\Desktop\CRM\crm_api\venv\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\CPT-003\Desktop\CRM\crm_api\venv\Lib\site-packages\rest_framework\views.py", line 515, in dispatch
    response = self.handle_exception(exc)
  File "C:\Users\CPT-003\Desktop\CRM\crm_api\venv\Lib\site-packages\rest_framework\views.py", line 475, in handle_exception
    self.raise_uncaught_exception(exc)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^
  File "C:\Users\CPT-003\Desktop\CRM\crm_api\venv\Lib\site-packages\rest_framework\views.py", line 486, in raise_uncaught_exception
    raise exc
  File "C:\Users\CPT-003\Desktop\CRM\crm_api\venv\Lib\site-packages\rest_framework\views.py", line 512, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\Users\CPT-003\Desktop\CRM\crm_api\core\views.py", line 202, in get
    config = TenantConfig.objects.get(tenant=tenant)
  File "C:\Users\CPT-003\Desktop\CRM\crm_api\venv\Lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "C:\Users\CPT-003\Desktop\CRM\crm_api\venv\Lib\site-packages\django\db\models\query.py", line 629, in get
    num = len(clone)
  File "C:\Users\CPT-003\Desktop\CRM\crm_api\venv\Lib\site-packages\django\db\models\query.py", line 366, in __len__
    self._fetch_all()
    ~~~~~~~~~~~~~~~^^
  File "C:\Users\CPT-003\Desktop\CRM\crm_api\venv\Lib\site-packages\django\db\models\query.py", line 1949, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
                         ~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\CPT-003\Desktop\CRM\crm_api\venv\Lib\site-packages\django\db\models\query.py", line 91, in __iter__
    results = compiler.execute_sql(
        chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size
    )
  File "C:\Users\CPT-003\Desktop\CRM\crm_api\venv\Lib\site-packages\django\db\models\sql\compiler.py", line 1623, in execute_sql
    cursor.execute(sql, params)
    ~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\Users\CPT-003\Desktop\CRM\crm_api\venv\Lib\site-packages\django\db\backends\utils.py", line 122, in execute
    return super().execute(sql, params)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\Users\CPT-003\Desktop\CRM\crm_api\venv\Lib\site-packages\django\db\backends\utils.py", line 79, in execute
    return self._execute_with_wrappers(
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        sql, params, many=False, executor=self._execute
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\CPT-003\Desktop\CRM\crm_api\venv\Lib\site-packages\django\db\backends\utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "C:\Users\CPT-003\Desktop\CRM\crm_api\venv\Lib\site-packages\django\db\backends\utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\CPT-003\Desktop\CRM\crm_api\venv\Lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\Users\CPT-003\Desktop\CRM\crm_api\venv\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
django.db.utils.ProgrammingError: column core_tenantconfig.email_templates does not exist
LINE 1: ...fig"."logo", "core_tenantconfig"."custom_fields", "core_tena...
                                                             ^

2025-07-10 09:34:30,516 [ERROR] django.server: "GET /api/tenant/config/ HTTP/1.1" 500 172898
2025-07-10 09:46:06,647 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2025-07-10 09:47:40,058 [INFO] django.server: "OPTIONS /api/talent-engine-job-applications/published-requisitions-with-shortlisted/ HTTP/1.1" 200 0
2025-07-10 09:47:40,060 [INFO] django.server: "OPTIONS /api/talent-engine-job-applications/published-requisitions-with-shortlisted/ HTTP/1.1" 200 0
2025-07-10 09:47:40,218 [INFO] django.server: "GET /api/talent-engine-job-applications/published-requisitions-with-shortlisted/ HTTP/1.1" 200 10751
2025-07-10 09:47:40,218 [INFO] django.server: "GET /api/talent-engine-job-applications/published-requisitions-with-shortlisted/ HTTP/1.1" 200 10751
2025-07-10 09:47:41,599 [INFO] django.server: "OPTIONS /api/talent-engine-job-applications/schedules/ HTTP/1.1" 200 0
2025-07-10 09:47:41,601 [INFO] django.server: "OPTIONS /api/talent-engine-job-applications/schedules/ HTTP/1.1" 200 0
2025-07-10 09:47:41,731 [INFO] django.server: "GET /api/talent-engine-job-applications/schedules/ HTTP/1.1" 200 7513
2025-07-10 09:47:41,731 [INFO] django.server: "GET /api/talent-engine-job-applications/schedules/ HTTP/1.1" 200 7513
2025-07-10 09:47:51,381 [WARNING] django.request: Not Found: /api/tenant/config/
2025-07-10 09:47:51,381 [WARNING] django.request: Not Found: /api/tenant/config/
2025-07-10 09:47:51,382 [WARNING] django.server: "GET /api/tenant/config/ HTTP/1.1" 404 54
2025-07-10 09:47:51,383 [WARNING] django.server: "GET /api/tenant/config/ HTTP/1.1" 404 54
2025-07-10 09:48:00,025 [WARNING] django.request: Not Found: /api/tenant/config/
2025-07-10 09:48:00,026 [WARNING] django.server: "PATCH /api/tenant/config/ HTTP/1.1" 404 54
2025-07-10 09:49:44,500 [INFO] core: Listing tenants: [2] for tenant proliance
2025-07-10 09:49:44,501 [INFO] django.server: "GET /api/tenant/tenants/ HTTP/1.1" 200 379
2025-07-10 09:49:57,357 [WARNING] django.request: Not Found: /api/tenant/config/
2025-07-10 09:49:57,358 [WARNING] django.server: "GET /api/tenant/config/ HTTP/1.1" 404 54
2025-07-10 09:51:44,341 [INFO] django.utils.autoreload: C:\Users\CPT-003\Desktop\CRM\crm_api\core\views.py changed, reloading.
2025-07-10 09:51:46,636 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2025-07-10 09:55:04,293 [INFO] django.utils.autoreload: C:\Users\CPT-003\Desktop\CRM\crm_api\core\serializers.py changed, reloading.
2025-07-10 09:55:07,911 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2025-07-10 10:11:47,218 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2025-07-10 10:12:01,209 [INFO] django.server: "GET /api/tenant/config/ HTTP/1.1" 200 1453
2025-07-10 10:13:20,045 [INFO] django.server: "GET /api/token/validate/ HTTP/1.1" 200 372
2025-07-10 10:13:20,046 [INFO] django.server: "GET /api/token/validate/ HTTP/1.1" 200 372
2025-07-10 10:13:20,283 [INFO] django.server: "GET /api/tenant/config/ HTTP/1.1" 200 1453
2025-07-10 10:13:20,325 [INFO] django.server: "GET /api/tenant/config/ HTTP/1.1" 200 1453
2025-07-10 10:14:17,289 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2025-07-10 10:14:30,540 [INFO] django.server: "GET /api/token/validate/ HTTP/1.1" 200 372
2025-07-10 10:14:30,540 [INFO] django.server: "GET /api/token/validate/ HTTP/1.1" 200 372
2025-07-10 10:14:30,757 [INFO] django.server: "GET /api/tenant/config/ HTTP/1.1" 200 1453
2025-07-10 10:14:30,764 [INFO] django.server: "GET /api/tenant/config/ HTTP/1.1" 200 1453
2025-07-10 10:15:31,767 [INFO] core: Tenant config updated for tenant proliance
2025-07-10 10:15:31,768 [INFO] django.server: "PATCH /api/tenant/config/ HTTP/1.1" 200 1001
2025-07-10 10:15:37,011 [INFO] django.server: "GET /api/token/validate/ HTTP/1.1" 200 372
2025-07-10 10:15:37,021 [INFO] django.server: "GET /api/token/validate/ HTTP/1.1" 200 372
2025-07-10 10:15:37,235 [INFO] django.server: "GET /api/tenant/config/ HTTP/1.1" 200 1001
2025-07-10 10:15:37,253 [INFO] django.server: "GET /api/tenant/config/ HTTP/1.1" 200 1001
