2025-06-26 02:16:40,218 [INFO] talent_engine: Job requisition accessed via link: Instrumentation Engineer Man for tenant proliance
2025-06-26 02:16:40,228 [INFO] django.server: "GET /api/talent-engine/requisitions/by-link/proliance-instrumentation-engineer-man-9ea58c8c/ HTTP/1.1" 200 2658
2025-06-26 02:17:05,185 [INFO] talent_engine: Job requisition accessed via link: Instrumentation Engineer Man for tenant proliance
2025-06-26 02:17:05,192 [INFO] django.server: "GET /api/talent-engine/requisitions/by-link/proliance-instrumentation-engineer-man-9ea58c8c/ HTTP/1.1" 200 2658
2025-06-26 02:18:14,211 [INFO] talent_engine: Job requisition accessed via link: Instrumentation Engineer Man for tenant proliance
2025-06-26 02:18:14,217 [INFO] django.server: "GET /api/talent-engine/requisitions/by-link/proliance-instrumentation-engineer-man-9ea58c8c/ HTTP/1.1" 200 2658
2025-06-26 02:18:14,287 [INFO] talent_engine: Job requisition accessed via link: Instrumentation Engineer Man for tenant proliance
2025-06-26 02:18:14,292 [INFO] django.server: "GET /api/talent-engine/requisitions/by-link/proliance-instrumentation-engineer-man-9ea58c8c/ HTTP/1.1" 200 2658
2025-06-26 02:18:37,202 [INFO] talent_engine: Job requisition accessed via link: Instrumentation Engineer Man for tenant proliance
2025-06-26 02:18:37,209 [INFO] django.server: "GET /api/talent-engine/requisitions/by-link/proliance-instrumentation-engineer-man-9ea58c8c/ HTTP/1.1" 200 2658
2025-06-26 02:21:15,188 [INFO] talent_engine: Job requisition accessed via link: Instrumentation Engineer Man for tenant proliance
2025-06-26 02:21:15,195 [INFO] django.server: "GET /api/talent-engine/requisitions/by-link/proliance-instrumentation-engineer-man-9ea58c8c/ HTTP/1.1" 200 2658
2025-06-26 02:22:39,182 [INFO] talent_engine: Job requisition accessed via link: Instrumentation Engineer Man for tenant proliance
2025-06-26 02:22:39,191 [INFO] django.server: "GET /api/talent-engine/requisitions/by-link/proliance-instrumentation-engineer-man-9ea58c8c/ HTTP/1.1" 200 2658
2025-06-26 02:22:39,258 [INFO] talent_engine: Job requisition accessed via link: Instrumentation Engineer Man for tenant proliance
2025-06-26 02:22:39,263 [INFO] django.server: "GET /api/talent-engine/requisitions/by-link/proliance-instrumentation-engineer-man-9ea58c8c/ HTTP/1.1" 200 2658
2025-06-26 02:23:17,182 [INFO] talent_engine: Job requisition accessed via link: Instrumentation Engineer Man for tenant proliance
2025-06-26 02:23:17,188 [INFO] django.server: "GET /api/talent-engine/requisitions/by-link/proliance-instrumentation-engineer-man-9ea58c8c/ HTTP/1.1" 200 2658
2025-06-26 02:24:21,192 [INFO] talent_engine: Job requisition accessed via link: Instrumentation Engineer Man for tenant proliance
2025-06-26 02:24:21,200 [INFO] django.server: "GET /api/talent-engine/requisitions/by-link/proliance-instrumentation-engineer-man-9ea58c8c/ HTTP/1.1" 200 2658
2025-06-26 02:24:28,301 [INFO] talent_engine: Job requisition accessed via link: Instrumentation Engineer Man for tenant proliance
2025-06-26 02:24:28,308 [INFO] django.server: "GET /api/talent-engine/requisitions/by-link/proliance-instrumentation-engineer-man-9ea58c8c/ HTTP/1.1" 200 2658
2025-06-26 02:25:08,529 [WARNING] django.request: Bad Request: /api/talent-engine-job-applications/applications/
2025-06-26 02:25:08,529 [WARNING] django.server: "POST /api/talent-engine-job-applications/applications/ HTTP/1.1" 400 235
2025-06-26 02:28:09,815 [INFO] django.utils.autoreload: C:\Users\CPT-003\Desktop\Proliance Source Codes\Backend\crm_api\job_application\models.py changed, reloading.
2025-06-26 02:28:11,847 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2025-06-26 02:28:22,796 [INFO] django.utils.autoreload: C:\Users\CPT-003\Desktop\Proliance Source Codes\Backend\crm_api\job_application\serializers.py changed, reloading.
2025-06-26 02:28:24,547 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2025-06-26 02:28:27,729 [INFO] django.utils.autoreload: C:\Users\CPT-003\Desktop\Proliance Source Codes\Backend\crm_api\job_application\serializers.py changed, reloading.
2025-06-26 02:28:29,603 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2025-06-26 02:51:33,935 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2025-06-26 02:52:02,631 [INFO] django.server: "POST /api/token/ HTTP/1.1" 200 1086
2025-06-26 02:52:02,799 [INFO] django.server: "GET /api/token/validate/ HTTP/1.1" 200 502
2025-06-26 02:52:02,938 [INFO] django.server: "GET /api/token/validate/ HTTP/1.1" 200 502
2025-06-26 02:52:09,463 [INFO] django.server: "GET /api/talent-engine/requisitions/ HTTP/1.1" 200 15365
2025-06-26 02:52:09,604 [INFO] django.server: "GET /api/talent-engine/requisitions/ HTTP/1.1" 200 15365
2025-06-26 02:53:00,226 [INFO] django.server: "GET /api/talent-engine/requisitions/ HTTP/1.1" 200 15365
2025-06-26 02:53:51,216 [INFO] django.server: "GET /api/talent-engine/requisitions/ HTTP/1.1" 200 15365
2025-06-26 02:54:21,923 [ERROR] django.request: Internal Server Error: /api/talent-engine/requisitions/
Traceback (most recent call last):
  File "C:\Users\CPT-003\Desktop\Proliance Source Codes\Backend\crm_api\venv\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
psycopg2.errors.StringDataRightTruncation: value too long for type character varying(10)


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\CPT-003\Desktop\Proliance Source Codes\Backend\crm_api\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\CPT-003\Desktop\Proliance Source Codes\Backend\crm_api\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\CPT-003\Desktop\Proliance Source Codes\Backend\crm_api\venv\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "C:\Users\CPT-003\Desktop\Proliance Source Codes\Backend\crm_api\venv\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\CPT-003\Desktop\Proliance Source Codes\Backend\crm_api\venv\Lib\site-packages\rest_framework\views.py", line 515, in dispatch
    response = self.handle_exception(exc)
  File "C:\Users\CPT-003\Desktop\Proliance Source Codes\Backend\crm_api\venv\Lib\site-packages\rest_framework\views.py", line 475, in handle_exception
    self.raise_uncaught_exception(exc)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^
  File "C:\Users\CPT-003\Desktop\Proliance Source Codes\Backend\crm_api\venv\Lib\site-packages\rest_framework\views.py", line 486, in raise_uncaught_exception
    raise exc
  File "C:\Users\CPT-003\Desktop\Proliance Source Codes\Backend\crm_api\venv\Lib\site-packages\rest_framework\views.py", line 512, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\Users\CPT-003\Desktop\Proliance Source Codes\Backend\crm_api\venv\Lib\site-packages\rest_framework\generics.py", line 246, in post
    return self.create(request, *args, **kwargs)
           ~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\CPT-003\Desktop\Proliance Source Codes\Backend\crm_api\venv\Lib\site-packages\rest_framework\mixins.py", line 19, in create
    self.perform_create(serializer)
    ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^
  File "C:\Users\CPT-003\Desktop\Proliance Source Codes\Backend\crm_api\talent_engine\views.py", line 69, in perform_create
    serializer.save(tenant=tenant)
    ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "C:\Users\CPT-003\Desktop\Proliance Source Codes\Backend\crm_api\venv\Lib\site-packages\rest_framework\serializers.py", line 210, in save
    self.instance = self.create(validated_data)
                    ~~~~~~~~~~~^^^^^^^^^^^^^^^^
  File "C:\Users\CPT-003\Desktop\Proliance Source Codes\Backend\crm_api\venv\Lib\site-packages\rest_framework\serializers.py", line 991, in create
    instance = ModelClass._default_manager.create(**validated_data)
  File "C:\Users\CPT-003\Desktop\Proliance Source Codes\Backend\crm_api\venv\Lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "C:\Users\CPT-003\Desktop\Proliance Source Codes\Backend\crm_api\venv\Lib\site-packages\django\db\models\query.py", line 663, in create
    obj.save(force_insert=True, using=self.db)
    ~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\CPT-003\Desktop\Proliance Source Codes\Backend\crm_api\talent_engine\models.py", line 117, in save
    super().save(*args, **kwargs)
    ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "C:\Users\CPT-003\Desktop\Proliance Source Codes\Backend\crm_api\venv\Lib\site-packages\django\db\models\base.py", line 902, in save
    self.save_base(
    ~~~~~~~~~~~~~~^
        using=using,
        ^^^^^^^^^^^^
    ...<2 lines>...
        update_fields=update_fields,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\CPT-003\Desktop\Proliance Source Codes\Backend\crm_api\venv\Lib\site-packages\django\db\models\base.py", line 1008, in save_base
    updated = self._save_table(
        raw,
    ...<4 lines>...
        update_fields,
    )
  File "C:\Users\CPT-003\Desktop\Proliance Source Codes\Backend\crm_api\venv\Lib\site-packages\django\db\models\base.py", line 1169, in _save_table
    results = self._do_insert(
        cls._base_manager, using, fields, returning_fields, raw
    )
  File "C:\Users\CPT-003\Desktop\Proliance Source Codes\Backend\crm_api\venv\Lib\site-packages\django\db\models\base.py", line 1210, in _do_insert
    return manager._insert(
           ~~~~~~~~~~~~~~~^
        [self],
        ^^^^^^^
    ...<3 lines>...
        raw=raw,
        ^^^^^^^^
    )
    ^
  File "C:\Users\CPT-003\Desktop\Proliance Source Codes\Backend\crm_api\venv\Lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "C:\Users\CPT-003\Desktop\Proliance Source Codes\Backend\crm_api\venv\Lib\site-packages\django\db\models\query.py", line 1868, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
  File "C:\Users\CPT-003\Desktop\Proliance Source Codes\Backend\crm_api\venv\Lib\site-packages\django\db\models\sql\compiler.py", line 1882, in execute_sql
    cursor.execute(sql, params)
    ~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\Users\CPT-003\Desktop\Proliance Source Codes\Backend\crm_api\venv\Lib\site-packages\django\db\backends\utils.py", line 79, in execute
    return self._execute_with_wrappers(
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        sql, params, many=False, executor=self._execute
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\CPT-003\Desktop\Proliance Source Codes\Backend\crm_api\venv\Lib\site-packages\django\db\backends\utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "C:\Users\CPT-003\Desktop\Proliance Source Codes\Backend\crm_api\venv\Lib\site-packages\django\db\backends\utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\CPT-003\Desktop\Proliance Source Codes\Backend\crm_api\venv\Lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\Users\CPT-003\Desktop\Proliance Source Codes\Backend\crm_api\venv\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
django.db.utils.DataError: value too long for type character varying(10)

2025-06-26 02:54:22,017 [ERROR] django.server: "POST /api/talent-engine/requisitions/ HTTP/1.1" 500 145
2025-06-26 02:55:41,705 [INFO] django.utils.autoreload: C:\Users\CPT-003\Desktop\Proliance Source Codes\Backend\crm_api\talent_engine\models.py changed, reloading.
2025-06-26 02:55:43,740 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2025-06-26 02:56:07,032 [INFO] django.utils.autoreload: C:\Users\CPT-003\Desktop\Proliance Source Codes\Backend\crm_api\job_application\models.py changed, reloading.
2025-06-26 02:56:08,834 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2025-06-26 02:56:11,350 [INFO] django.utils.autoreload: C:\Users\CPT-003\Desktop\Proliance Source Codes\Backend\crm_api\job_application\models.py changed, reloading.
2025-06-26 02:56:13,596 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2025-06-26 02:56:17,491 [INFO] django.server: "GET /api/token/validate/ HTTP/1.1" 200 502
2025-06-26 02:56:17,708 [INFO] django.server: "GET /api/token/validate/ HTTP/1.1" 200 502
2025-06-26 02:56:18,030 [INFO] django.server: "GET /api/talent-engine/requisitions/ HTTP/1.1" 200 15365
2025-06-26 02:56:18,314 [INFO] django.server: "GET /api/talent-engine/requisitions/ HTTP/1.1" 200 15365
2025-06-26 02:57:08,341 [INFO] django.server: "GET /api/talent-engine/requisitions/ HTTP/1.1" 200 15365
2025-06-26 02:57:32,614 [ERROR] django.request: Internal Server Error: /api/talent-engine/requisitions/
Traceback (most recent call last):
  File "C:\Users\CPT-003\Desktop\Proliance Source Codes\Backend\crm_api\venv\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
psycopg2.errors.StringDataRightTruncation: value too long for type character varying(10)


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\CPT-003\Desktop\Proliance Source Codes\Backend\crm_api\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\CPT-003\Desktop\Proliance Source Codes\Backend\crm_api\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\CPT-003\Desktop\Proliance Source Codes\Backend\crm_api\venv\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "C:\Users\CPT-003\Desktop\Proliance Source Codes\Backend\crm_api\venv\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\CPT-003\Desktop\Proliance Source Codes\Backend\crm_api\venv\Lib\site-packages\rest_framework\views.py", line 515, in dispatch
    response = self.handle_exception(exc)
  File "C:\Users\CPT-003\Desktop\Proliance Source Codes\Backend\crm_api\venv\Lib\site-packages\rest_framework\views.py", line 475, in handle_exception
    self.raise_uncaught_exception(exc)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^
  File "C:\Users\CPT-003\Desktop\Proliance Source Codes\Backend\crm_api\venv\Lib\site-packages\rest_framework\views.py", line 486, in raise_uncaught_exception
    raise exc
  File "C:\Users\CPT-003\Desktop\Proliance Source Codes\Backend\crm_api\venv\Lib\site-packages\rest_framework\views.py", line 512, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\Users\CPT-003\Desktop\Proliance Source Codes\Backend\crm_api\venv\Lib\site-packages\rest_framework\generics.py", line 246, in post
    return self.create(request, *args, **kwargs)
           ~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\CPT-003\Desktop\Proliance Source Codes\Backend\crm_api\venv\Lib\site-packages\rest_framework\mixins.py", line 19, in create
    self.perform_create(serializer)
    ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^
  File "C:\Users\CPT-003\Desktop\Proliance Source Codes\Backend\crm_api\talent_engine\views.py", line 69, in perform_create
    serializer.save(tenant=tenant)
    ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "C:\Users\CPT-003\Desktop\Proliance Source Codes\Backend\crm_api\venv\Lib\site-packages\rest_framework\serializers.py", line 210, in save
    self.instance = self.create(validated_data)
                    ~~~~~~~~~~~^^^^^^^^^^^^^^^^
  File "C:\Users\CPT-003\Desktop\Proliance Source Codes\Backend\crm_api\venv\Lib\site-packages\rest_framework\serializers.py", line 991, in create
    instance = ModelClass._default_manager.create(**validated_data)
  File "C:\Users\CPT-003\Desktop\Proliance Source Codes\Backend\crm_api\venv\Lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "C:\Users\CPT-003\Desktop\Proliance Source Codes\Backend\crm_api\venv\Lib\site-packages\django\db\models\query.py", line 663, in create
    obj.save(force_insert=True, using=self.db)
    ~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\CPT-003\Desktop\Proliance Source Codes\Backend\crm_api\talent_engine\models.py", line 118, in save
    super().save(*args, **kwargs)
    ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "C:\Users\CPT-003\Desktop\Proliance Source Codes\Backend\crm_api\venv\Lib\site-packages\django\db\models\base.py", line 902, in save
    self.save_base(
    ~~~~~~~~~~~~~~^
        using=using,
        ^^^^^^^^^^^^
    ...<2 lines>...
        update_fields=update_fields,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\CPT-003\Desktop\Proliance Source Codes\Backend\crm_api\venv\Lib\site-packages\django\db\models\base.py", line 1008, in save_base
    updated = self._save_table(
        raw,
    ...<4 lines>...
        update_fields,
    )
  File "C:\Users\CPT-003\Desktop\Proliance Source Codes\Backend\crm_api\venv\Lib\site-packages\django\db\models\base.py", line 1169, in _save_table
    results = self._do_insert(
        cls._base_manager, using, fields, returning_fields, raw
    )
  File "C:\Users\CPT-003\Desktop\Proliance Source Codes\Backend\crm_api\venv\Lib\site-packages\django\db\models\base.py", line 1210, in _do_insert
    return manager._insert(
           ~~~~~~~~~~~~~~~^
        [self],
        ^^^^^^^
    ...<3 lines>...
        raw=raw,
        ^^^^^^^^
    )
    ^
  File "C:\Users\CPT-003\Desktop\Proliance Source Codes\Backend\crm_api\venv\Lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "C:\Users\CPT-003\Desktop\Proliance Source Codes\Backend\crm_api\venv\Lib\site-packages\django\db\models\query.py", line 1868, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
  File "C:\Users\CPT-003\Desktop\Proliance Source Codes\Backend\crm_api\venv\Lib\site-packages\django\db\models\sql\compiler.py", line 1882, in execute_sql
    cursor.execute(sql, params)
    ~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\Users\CPT-003\Desktop\Proliance Source Codes\Backend\crm_api\venv\Lib\site-packages\django\db\backends\utils.py", line 79, in execute
    return self._execute_with_wrappers(
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        sql, params, many=False, executor=self._execute
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\CPT-003\Desktop\Proliance Source Codes\Backend\crm_api\venv\Lib\site-packages\django\db\backends\utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "C:\Users\CPT-003\Desktop\Proliance Source Codes\Backend\crm_api\venv\Lib\site-packages\django\db\backends\utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\CPT-003\Desktop\Proliance Source Codes\Backend\crm_api\venv\Lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\Users\CPT-003\Desktop\Proliance Source Codes\Backend\crm_api\venv\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
django.db.utils.DataError: value too long for type character varying(10)

2025-06-26 02:57:32,626 [ERROR] django.server: "POST /api/talent-engine/requisitions/ HTTP/1.1" 500 145
